name: 'PR Review with Progress Tracking'
description: 'Perform PR reviews with Checksum and progress tracking using private action'
inputs:
  cs_api_key:
    description: 'Checksum API KEY'
    required: true

permissions:  # â† Add this section
    contents: read
    pull-requests: write
    issues: write
    statuses: write

runs:
  using: 'composite'
  steps:
    - name: Fetch authentication credentials
      id: auth-credentials
      shell: bash
      run: |
        response=$(curl -sS -X POST https://aiagents-770070026559.us-central1.run.app/cq-agent/authenticate \
          -H "Content-Type: application/json" \
          -d '{"cs_api_key": "${{ inputs.cs_api_key }}"}')
        
        gh_id=$(echo "$response" | jq -r '.gh_id')
        gh_key_escaped=$(echo "$response" | jq -r '.gh_key')
        
        # Mask the ID
        echo "::add-mask::$gh_id"
        
        # Write outputs
        echo "gh_id=$gh_id" >> $GITHUB_OUTPUT
        
        # Write the private key with proper newline handling
        {
          echo "gh_key<<EOF"
          printf '%b\n' "$gh_key_escaped"
          echo "EOF"
        } >> $GITHUB_OUTPUT
        
        # Mask the key after writing (avoid masking before to prevent output issues)
        printf '%b\n' "$gh_key_escaped" | while IFS= read -r line; do
          [[ -n "$line" ]] && echo "::add-mask::$line"
        done

    - name: Generate GitHub Clone token
      id: clone-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ steps.auth-credentials.outputs.gh_id }}
        private-key: ${{ steps.auth-credentials.outputs.gh_key }}
        owner: checksum-ai
        repository: pr-agent-priv

    - name: Generate PR Review Token
      id: pr-review-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ steps.auth-credentials.outputs.gh_id }}
        private-key: ${{ steps.auth-credentials.outputs.gh_key }}
    
    - name: Check out private action repo
      uses: actions/checkout@v4
      with:
        repository: checksum-ai/pr-agent-priv
        token: ${{ steps.clone-token.outputs.token }} # Use the secret you created
        path: ./.github/private-actions/pr-agent-priv # Check it out to a specific path
    - name: PR Review with Progress Tracking
      uses: ./.github/private-actions/pr-agent-priv
      with:
        cs_api_key: ${{ inputs.cs_api_key }}
        gh_token: ${{ steps.pr-review-token.outputs.token }}
