name: 'PR Review with Progress Tracking'
description: 'Perform PR reviews with Checksum and progress tracking'
inputs:
  cs_api_key:
    description: 'Checksum API KEY'
    required: true

permissions:  # ← Add this section
    contents: read
    pull-requests: write
    issues: write
    statuses: write

runs:
  using: 'composite'
  steps:
    - name: Fetch authentication credentials
      id: auth-credentials
      shell: bash
      run: |
        response=$(curl -sS -X POST https://aiagents-770070026559.us-central1.run.app/cq-agent/authenticate \
          -H "Content-Type: application/json" \
          -d '{"cs_api_key": "${{ inputs.cs_api_key }}"}')
        
        # Extract values from response
        gh_id=$(echo "$response" | jq -r '.gh_id')
        gh_key_raw=$(echo "$response" | jq -r '.gh_key')
        
        # Convert escaped newlines to actual newlines in the private key
        gh_key=$(echo "$gh_key_raw" | sed 's/\\n/\n/g')
        
        # Mask sensitive values from logs
        echo "::add-mask::$gh_id"
        # Mask each line of the private key separately
        while IFS= read -r line; do
          [[ -n "$line" ]] && echo "::add-mask::$line"
        done <<< "$gh_key"
        # Also mask common private key patterns to catch any missed lines
        echo "::add-mask::BEGIN"
        echo "::add-mask::END"
        echo "::add-mask::PRIVATE KEY"
        
        # Set outputs for use in subsequent steps
        echo "gh_id=$gh_id" >> $GITHUB_OUTPUT
        echo "gh_key<<EOF" >> $GITHUB_OUTPUT
        echo "$gh_key" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Generate GitHub Clone token
      id: clone-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ steps.auth-credentials.outputs.gh_id }}
        private-key: ${{ steps.auth-credentials.outputs.gh_key }}
        owner: checksum-ai
        repository: pr-agent-priv

    - name: Generate PR Review Token
      id: pr-review-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ steps.auth-credentials.outputs.gh_id }}
        private-key: ${{ steps.auth-credentials.outputs.gh_key }}
    
    - name: Check out private action repo
      uses: actions/checkout@v4
      with:
        repository: checksum-ai/pr-agent-priv
        token: ${{ steps.clone-token.outputs.token }} # Use the secret you created
        path: ./.github/private-actions/pr-agent-priv # Check it out to a specific path
    - name: PR Review with Progress Tracking
      uses: ./.github/private-actions/pr-agent-priv
      with:
        cs_api_key: ${{ inputs.cs_api_key }}
        gh_token: ${{ steps.pr-review-token.outputs.token }}
