name: 'Checksum CI Guard'
description: 'AI-powered code review for pull requests (legacy path - use ci-guard/)'
author: 'Checksum AI'

branding:
  icon: 'shield'
  color: 'blue'

inputs:
  checksum_api_key:
    description: 'Your Checksum API key'
    required: true
  pr_number:
    description: 'Pull request number'
    required: true
  pr_title:
    description: 'Pull request title'
    required: true
  pr_url:
    description: 'Pull request URL'
    required: true
  base_sha:
    description: 'Base commit SHA'
    required: true
  head_sha:
    description: 'Head commit SHA'
    required: true
  pr_body:
    description: 'Pull request body/description'
    required: false
    default: ''
  extra_context:
    description: 'Additional context to provide to the reviewer (optional)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Run CI Guard
      uses: checksum-ai/checksum-action/ci-guard@main
      with:
        checksum_api_key: ${{ inputs.checksum_api_key }}
        pr_number: ${{ inputs.pr_number }}
        pr_title: ${{ inputs.pr_title }}
        pr_url: ${{ inputs.pr_url }}
        base_sha: ${{ inputs.base_sha }}
        head_sha: ${{ inputs.head_sha }}
        pr_body: ${{ inputs.pr_body }}
        extra_context: ${{ inputs.extra_context }}
