checksum-pr-review:
  image: ubuntu:latest

  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

  variables:
    GIT_DEPTH: 0

  before_script:
    - apt-get update && apt-get install -y curl jq git ripgrep

  script:
    # Install PR Testing Agent
    - curl -fsSL "https://storage.googleapis.com/checksum-agent-public/install.sh?$(date +%s)" | bash -s -- --pr-review

    # Run PR Testing
    - |
      PROMPT="Review MR !$CI_MERGE_REQUEST_IID in $CI_PROJECT_PATH.

      MR Title: $CI_MERGE_REQUEST_TITLE
      MR URL: $CI_PROJECT_URL/-/merge_requests/$CI_MERGE_REQUEST_IID
      Base SHA: $CI_MERGE_REQUEST_DIFF_BASE_SHA
      Head SHA: $CI_COMMIT_SHA

      MR Description:
      $CI_MERGE_REQUEST_DESCRIPTION

      Use 'git diff $CI_MERGE_REQUEST_DIFF_BASE_SHA..$CI_COMMIT_SHA' to see the changes.

      To post comments, use the GitLab API:
      curl --request POST \\
        --header \"JOB-TOKEN: \$CI_JOB_TOKEN\" \\
        --form \"body=Your comment here\" \\
        \"\$CI_API_V4_URL/projects/\$CI_PROJECT_ID/merge_requests/\$CI_MERGE_REQUEST_IID/notes\""

      ~/.checksumai/callagents.sh pull-request-tester "$PROMPT"
