# Checksum CI Guard - Base Template
# Users extend this job and provide required variables
#
# Usage:
#   include:
#     - remote: 'https://raw.githubusercontent.com/checksum-ai/checksum-action/main/ci-guard/gitlab-ci.yml'
#
#   checksum-ci-guard:
#     extends: .checksum-ci-guard-base
#     rules:
#       - if: $CI_PIPELINE_SOURCE == "merge_request_event"
#     variables:
#       MR_NUMBER: $CI_MERGE_REQUEST_IID
#       PROJECT_PATH: $CI_PROJECT_PATH
#       MR_TITLE: $CI_MERGE_REQUEST_TITLE
#       MR_URL: "$CI_PROJECT_URL/-/merge_requests/$CI_MERGE_REQUEST_IID"
#       BASE_SHA: $CI_MERGE_REQUEST_DIFF_BASE_SHA
#       HEAD_SHA: $CI_COMMIT_SHA
#       MR_DESCRIPTION: $CI_MERGE_REQUEST_DESCRIPTION
#
# Note: Set CHECKSUM_API_KEY and GITLAB_TOKEN as CI/CD variables in Project Settings > CI/CD > Variables
#       Do NOT mark them as "Protected" (MR pipelines run on non-protected refs)
#
# Optional variables:
#     variables:
#       EXTRA_CONTEXT: "This is a Python project using pytest."  # Additional context for the reviewer
#       CHECKSUM_API_KEY_VAR: "MY_CUSTOM_API_KEY_NAME"  # If your API key variable has a different name
#       GITLAB_TOKEN_VAR: "MY_GITLAB_TOKEN_NAME"  # If your token variable has a different name 

.checksum-ci-guard-base:
  # ⚠️ REPLACE THIS IMAGE with one that has your project's runtime pre-installed!
  # The agent needs your test dependencies (Node.js, Python, etc.) to run tests.
  #
  # Examples:
  #   image: node:20-bookworm       # Node.js projects
  #   image: python:3.12-bookworm   # Python projects
  #   image: golang:1.22-bookworm   # Go projects
  #   image: rust:1.75-bookworm     # Rust projects
  #
  # ❌ Do NOT use Alpine images (e.g., node:20-alpine) - the agent binary requires glibc
  image: debian:bookworm-slim  # Default: minimal Debian (no runtimes pre-installed)

  variables:
    GIT_DEPTH: 0
    CHECKSUM_API_KEY_VAR: "CHECKSUM_API_KEY"  # Default variable name, can be overridden
    GITLAB_TOKEN_VAR: "GITLAB_TOKEN"  # Default variable name for GitLab token
    EXTRA_CONTEXT: ""  # Optional: Additional context for the reviewer

  before_script:
    - apt-get update && apt-get install -y --no-install-recommends curl jq bash ripgrep ca-certificates git
    # Install glab CLI from GitLab releases
    - |
      GLAB_VERSION=$(curl -sSL "https://gitlab.com/api/v4/projects/34675721/releases/permalink/latest" | jq -r '.tag_name' 2>/dev/null)
      if [ -z "$GLAB_VERSION" ] || [ "$GLAB_VERSION" = "null" ]; then
        echo "Error: Failed to fetch glab version from GitLab API"
        exit 1
      fi
      curl -fsSL "https://gitlab.com/gitlab-org/cli/-/releases/${GLAB_VERSION}/downloads/glab_${GLAB_VERSION#v}_linux_amd64.deb" -o /tmp/glab.deb
      dpkg -i /tmp/glab.deb && rm /tmp/glab.deb

  script:
    - |
      # Resolve API key and GitLab token from variable names (supports custom variable names)
      CHECKSUM_API_KEY="${!CHECKSUM_API_KEY_VAR}"
      GITLAB_TOKEN="${!GITLAB_TOKEN_VAR}"

      if [ -z "$CHECKSUM_API_KEY" ]; then
        echo "Error: $CHECKSUM_API_KEY_VAR is not set or empty"
        echo "Make sure the CI/CD variable is configured and NOT marked as 'Protected'"
        exit 1
      fi
      if [ -z "$GITLAB_TOKEN" ]; then
        echo "Error: $GITLAB_TOKEN_VAR is not set or empty"
        echo "Make sure the CI/CD variable is configured and NOT marked as 'Protected'"
        exit 1
      fi
      if [ -z "$MR_NUMBER" ]; then
        echo "Error: MR_NUMBER is required"
        exit 1
      fi

      # Authenticate glab CLI for MR comments
      glab auth login --token "$GITLAB_TOKEN" --hostname "$CI_SERVER_HOST"

      # Create .env file for the agent binary
      mkdir -p ~/.checksumai
      echo "CHECKSUM_API_KEY=$CHECKSUM_API_KEY" > ~/.checksumai/.env
      echo "GITLAB_TOKEN=$GITLAB_TOKEN" >> ~/.checksumai/.env
      chmod 600 ~/.checksumai/.env

      # Export GITLAB_TOKEN for the agent to use
      export GITLAB_TOKEN

      curl -fsSL "https://storage.googleapis.com/checksum-agent-public/install.sh?$(date +%s)" | bash -s -- --pr-review

      PROMPT="You are reviewing a GitLab Merge Request.

      Review MR !$MR_NUMBER in $PROJECT_PATH.

      MR Title: $MR_TITLE
      MR URL: $MR_URL
      Base SHA: $BASE_SHA
      Head SHA: $HEAD_SHA
      Pipeline ID: $CI_PIPELINE_ID
      Job ID: $CI_JOB_ID
      Project ID: $CI_PROJECT_ID

      MR Description:
      $MR_DESCRIPTION

      Use 'git diff $BASE_SHA...$HEAD_SHA' to see the changes.

      Use 'glab mr note $MR_NUMBER --message <comment>' to post comments to the MR."

      if [ -n "$EXTRA_CONTEXT" ]; then
        PROMPT="$PROMPT

      Additional Context:
      $EXTRA_CONTEXT"
      fi

      ~/.checksumai/callagents.sh pull-request-tester "$PROMPT"

      # Check for generated tests and upload to Checksum backend
      if find tmp -name "*.py" -o -name "*.md" -o -name "*.txt" 2>/dev/null | grep -q .; then
        echo "Generated tests found, preparing upload..."
        echo "HAS_TESTS=true" >> generated_tests.env

        # Build test_files JSON array from all files in tmp/
        TEST_FILES_JSON="[]"
        for file in tmp/*; do
          if [ -f "$file" ]; then
            filename=$(basename "$file")
            # Read file content and escape for JSON
            content=$(jq -Rs . < "$file")
            TEST_FILES_JSON=$(echo "$TEST_FILES_JSON" | jq --arg fn "$filename" --argjson content "$content" '. + [{filename: $fn, content: $content}]')
          fi
        done

        # Build request body for new CI Guard API
        REQUEST_BODY=$(jq -n \
          --arg repo "$PROJECT_PATH" \
          --arg pr_number "$MR_NUMBER" \
          --arg pr_title "$MR_TITLE" \
          --arg pr_description "${MR_DESCRIPTION:-}" \
          --arg pr_url "$MR_URL" \
          --arg base_sha "$BASE_SHA" \
          --arg head_sha "$HEAD_SHA" \
          --argjson test_files "$TEST_FILES_JSON" \
          '{
            repo: $repo,
            pr_number: ($pr_number | tonumber),
            pr_title: $pr_title,
            pr_description: $pr_description,
            pr_url: $pr_url,
            base_sha: $base_sha,
            head_sha: $head_sha,
            test_files: $test_files
          }')

        echo "Uploading to Checksum CI Guard API..."
        HTTP_RESPONSE=$(curl -sS -w "\n%{http_code}" -X POST \
          "https://aiagents.checksum.ai/agent-services/ci-guard/runs" \
          -H "x-api-key: $CHECKSUM_API_KEY" \
          -H "Content-Type: application/json" \
          -d "$REQUEST_BODY")

        HTTP_CODE=$(echo "$HTTP_RESPONSE" | tail -n1)
        HTTP_BODY=$(echo "$HTTP_RESPONSE" | sed '$d')

        if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "201" ]; then
          echo "Tests uploaded to Checksum successfully"
          echo "Response: $HTTP_BODY"
        else
          echo "Warning: Failed to upload tests to Checksum (HTTP $HTTP_CODE): $HTTP_BODY"
        fi
      else
        echo "No test files found in tmp/"
        echo "HAS_TESTS=false" >> generated_tests.env
      fi

  artifacts:
    paths:
      - tmp/
    expire_in: 60 days
    when: always
    reports:
      dotenv: generated_tests.env
