# Checksum CI Guard - Base Template
# Users extend this job and provide required variables
#
# Usage:
#   include:
#     - remote: 'https://raw.githubusercontent.com/checksum-ai/checksum-action/main/ci-guard/gitlab-ci.yml'
#
#   checksum-ci-guard:
#     extends: .checksum-ci-guard-base
#     rules:
#       - if: $CI_PIPELINE_SOURCE == "merge_request_event"
#     variables:
#       MR_NUMBER: $CI_MERGE_REQUEST_IID
#       PROJECT_PATH: $CI_PROJECT_PATH
#       MR_TITLE: $CI_MERGE_REQUEST_TITLE
#       MR_URL: "$CI_PROJECT_URL/-/merge_requests/$CI_MERGE_REQUEST_IID"
#       BASE_SHA: $CI_MERGE_REQUEST_DIFF_BASE_SHA
#       HEAD_SHA: $CI_COMMIT_SHA
#       MR_DESCRIPTION: $CI_MERGE_REQUEST_DESCRIPTION
#
# Note: Set CHECKSUM_API_KEY and GITLAB_TOKEN as CI/CD variables in Project Settings > CI/CD > Variables
#       Do NOT mark them as "Protected" (MR pipelines run on non-protected refs)
#
# Optional variables:
#     variables:
#       EXTRA_CONTEXT: "This is a Python project using pytest."  # Additional context for the reviewer
#       CHECKSUM_API_KEY_VAR: "MY_CUSTOM_API_KEY_NAME"  # If your API key variable has a different name
#       GITLAB_TOKEN_VAR: "MY_GITLAB_TOKEN_NAME"  # If your token variable has a different name

.checksum-ci-guard-base:
  image: debian:bookworm-slim  # Debian-based for glibc compatibility with e2e-agent binary

  variables:
    GIT_DEPTH: 0
    CHECKSUM_API_KEY_VAR: "CHECKSUM_API_KEY"  # Default variable name, can be overridden
    GITLAB_TOKEN_VAR: "GITLAB_TOKEN"  # Default variable name for GitLab token
    EXTRA_CONTEXT: ""  # Optional: Additional context for the reviewer

  before_script:
    - apt-get update && apt-get install -y --no-install-recommends curl jq bash ripgrep ca-certificates git
    # Install glab CLI from GitLab releases
    - |
      GLAB_VERSION=$(curl -s "https://gitlab.com/api/v4/projects/34675721/releases/permalink/latest" | jq -r '.tag_name')
      curl -fsSL "https://gitlab.com/gitlab-org/cli/-/releases/${GLAB_VERSION}/downloads/glab_${GLAB_VERSION#v}_linux_amd64.deb" -o /tmp/glab.deb
      dpkg -i /tmp/glab.deb && rm /tmp/glab.deb

  script:
    - |
      # Resolve API key and GitLab token from variable names (supports custom variable names)
      CHECKSUM_API_KEY="${!CHECKSUM_API_KEY_VAR}"
      GITLAB_TOKEN="${!GITLAB_TOKEN_VAR}"

      if [ -z "$CHECKSUM_API_KEY" ]; then
        echo "Error: $CHECKSUM_API_KEY_VAR is not set or empty"
        echo "Make sure the CI/CD variable is configured and NOT marked as 'Protected'"
        exit 1
      fi
      if [ -z "$GITLAB_TOKEN" ]; then
        echo "Error: $GITLAB_TOKEN_VAR is not set or empty"
        echo "Make sure the CI/CD variable is configured and NOT marked as 'Protected'"
        exit 1
      fi
      if [ -z "$MR_NUMBER" ]; then
        echo "Error: MR_NUMBER is required"
        exit 1
      fi

      # Authenticate glab CLI for MR comments
      glab auth login --token "$GITLAB_TOKEN" --hostname "$CI_SERVER_HOST"

      # Create .env file for the agent binary
      mkdir -p ~/.checksumai
      echo "CHECKSUM_API_KEY=$CHECKSUM_API_KEY" > ~/.checksumai/.env
      echo "GITLAB_TOKEN=$GITLAB_TOKEN" >> ~/.checksumai/.env
      chmod 600 ~/.checksumai/.env

      # Export GITLAB_TOKEN for the agent to use
      export GITLAB_TOKEN

      curl -fsSL "https://storage.googleapis.com/checksum-agent-public/install.sh?$(date +%s)" | bash -s -- --pr-review

      PROMPT="You are reviewing a GitLab Merge Request.

      Review MR !$MR_NUMBER in $PROJECT_PATH.

      MR Title: $MR_TITLE
      MR URL: $MR_URL
      Base SHA: $BASE_SHA
      Head SHA: $HEAD_SHA

      MR Description:
      $MR_DESCRIPTION

      Use 'git diff $BASE_SHA..$HEAD_SHA' to see the changes.

      Use 'glab mr note $MR_NUMBER --message <comment>' to post comments to the MR."

      if [ -n "$EXTRA_CONTEXT" ]; then
        PROMPT="$PROMPT

      Additional Context:
      $EXTRA_CONTEXT"
      fi

      ~/.checksumai/callagents.sh pull-request-tester "$PROMPT"
