# Checksum CI Guard - Base Template
# Users extend this job and provide required variables
#
# Usage:
#   include:
#     - remote: 'https://raw.githubusercontent.com/checksum-ai/checksum-action/main/ci-guard/gitlab-ci.yml'
#
#   checksum-ci-guard:
#     extends: .checksum-ci-guard-base
#     rules:
#       - if: $CI_PIPELINE_SOURCE == "merge_request_event"
#     variables:
#       MR_NUMBER: $CI_MERGE_REQUEST_IID
#       PROJECT_PATH: $CI_PROJECT_PATH
#       MR_TITLE: $CI_MERGE_REQUEST_TITLE
#       MR_URL: "$CI_PROJECT_URL/-/merge_requests/$CI_MERGE_REQUEST_IID"
#       BASE_SHA: $CI_MERGE_REQUEST_DIFF_BASE_SHA
#       HEAD_SHA: $CI_COMMIT_SHA
#       MR_DESCRIPTION: $CI_MERGE_REQUEST_DESCRIPTION
#
# Note: Set CHECKSUM_API_KEY and GITLAB_TOKEN as CI/CD variables in Project Settings > CI/CD > Variables
#       Do NOT mark them as "Protected" (MR pipelines run on non-protected refs)
#
# Optional variables:
#     variables:
#       EXTRA_CONTEXT: "This is a Python project using pytest."  # Additional context for the reviewer
#       CHECKSUM_API_KEY_VAR: "MY_CUSTOM_API_KEY_NAME"  # If your API key variable has a different name
#       GITLAB_TOKEN_VAR: "MY_GITLAB_TOKEN_NAME"  # If your token variable has a different name

.checksum-ci-guard-base:
  # ⚠️ REPLACE THIS IMAGE with one that has your project's runtime pre-installed!
  # The agent needs your test dependencies (Node.js, Python, etc.) to run tests.
  #
  # Examples:
  #   image: node:20-bookworm       # Node.js projects
  #   image: python:3.12-bookworm   # Python projects
  #   image: golang:1.22-bookworm   # Go projects
  #   image: rust:1.75-bookworm     # Rust projects
  #
  # ❌ Do NOT use Alpine images (e.g., node:20-alpine) - the agent binary requires glibc
  image: debian:bookworm-slim  # Default: minimal Debian (no runtimes pre-installed)

  variables:
    GIT_DEPTH: 0
    CHECKSUM_API_KEY_VAR: "CHECKSUM_API_KEY"  # Default variable name, can be overridden
    GITLAB_TOKEN_VAR: "GITLAB_TOKEN"  # Default variable name for GitLab token
    EXTRA_CONTEXT: ""  # Optional: Additional context for the reviewer

  before_script:
    - apt-get update && apt-get install -y --no-install-recommends curl jq bash ripgrep ca-certificates git
    # Install glab CLI from GitLab releases
    - |
      GLAB_VERSION=$(curl -sSL "https://gitlab.com/api/v4/projects/34675721/releases/permalink/latest" | jq -r '.tag_name' 2>/dev/null)
      if [ -z "$GLAB_VERSION" ] || [ "$GLAB_VERSION" = "null" ]; then
        echo "Error: Failed to fetch glab version from GitLab API"
        exit 1
      fi
      curl -fsSL "https://gitlab.com/gitlab-org/cli/-/releases/${GLAB_VERSION}/downloads/glab_${GLAB_VERSION#v}_linux_amd64.deb" -o /tmp/glab.deb
      dpkg -i /tmp/glab.deb && rm /tmp/glab.deb

  script:
    - |
      # Resolve API key and GitLab token from variable names (supports custom variable names)
      CHECKSUM_API_KEY="${!CHECKSUM_API_KEY_VAR}"
      GITLAB_TOKEN="${!GITLAB_TOKEN_VAR}"

      if [ -z "$CHECKSUM_API_KEY" ]; then
        echo "Error: $CHECKSUM_API_KEY_VAR is not set or empty"
        echo "Make sure the CI/CD variable is configured and NOT marked as 'Protected'"
        exit 1
      fi
      if [ -z "$GITLAB_TOKEN" ]; then
        echo "Error: $GITLAB_TOKEN_VAR is not set or empty"
        echo "Make sure the CI/CD variable is configured and NOT marked as 'Protected'"
        exit 1
      fi
      if [ -z "$MR_NUMBER" ]; then
        echo "Error: MR_NUMBER is required"
        exit 1
      fi

      # Authenticate glab CLI for MR comments
      glab auth login --token "$GITLAB_TOKEN" --hostname "$CI_SERVER_HOST"

      # Create .env file for the agent binary
      mkdir -p ~/.checksumai
      echo "CHECKSUM_API_KEY=$CHECKSUM_API_KEY" > ~/.checksumai/.env
      echo "GITLAB_TOKEN=$GITLAB_TOKEN" >> ~/.checksumai/.env
      chmod 600 ~/.checksumai/.env

      # Export GITLAB_TOKEN for the agent to use
      export GITLAB_TOKEN

      curl -fsSL "https://storage.googleapis.com/checksum-agent-public/install.sh?$(date +%s)" | bash -s -- --pr-review

      # Capture diff with file-level truncation
      capture_truncated_diff() {
        local BASE_SHA="$1"
        local HEAD_SHA="$2"
        local MAX_TOTAL=100000
        local MAX_PER_FILE=10000

        # Get list of changed files
        local CHANGED_FILES=$(git diff --name-only "$BASE_SHA".."$HEAD_SHA")

        if [ -z "$CHANGED_FILES" ]; then
          echo "No changes detected."
          return
        fi

        local FILE_COUNT=$(echo "$CHANGED_FILES" | wc -l | tr -d ' ')

        # Calculate per-file budget (divide total by file count, capped at MAX_PER_FILE)
        local PER_FILE_BUDGET=$((MAX_TOTAL / FILE_COUNT))
        [ "$PER_FILE_BUDGET" -gt "$MAX_PER_FILE" ] && PER_FILE_BUDGET=$MAX_PER_FILE

        # Output file list with stats
        echo "Changed files ($FILE_COUNT):"
        git diff --stat "$BASE_SHA".."$HEAD_SHA" | head -50
        echo ""
        echo "---"
        echo ""

        # Build truncated diff
        echo "$CHANGED_FILES" | while read -r FILE; do
          [ -z "$FILE" ] && continue

          local FILE_DIFF=$(git diff "$BASE_SHA".."$HEAD_SHA" -- "$FILE")
          local ACTUAL_SIZE=${#FILE_DIFF}

          if [ "$ACTUAL_SIZE" -gt "$PER_FILE_BUDGET" ]; then
            echo "${FILE_DIFF:0:$PER_FILE_BUDGET}"
            echo ""
            echo "... [${FILE} truncated: showing $PER_FILE_BUDGET of $ACTUAL_SIZE bytes. Use 'git diff $BASE_SHA..$HEAD_SHA -- \"$FILE\"' for full diff]"
            echo ""
          else
            echo "$FILE_DIFF"
          fi
        done
      }

      # Capture the diff
      DIFF_OUTPUT=$(capture_truncated_diff "$BASE_SHA" "$HEAD_SHA")

      PROMPT="You are reviewing a GitLab Merge Request.

      Review MR !$MR_NUMBER in $PROJECT_PATH.

      MR Title: $MR_TITLE
      MR URL: $MR_URL
      Base SHA: $BASE_SHA
      Head SHA: $HEAD_SHA

      MR Description:
      $MR_DESCRIPTION

      ## Changes

      $DIFF_OUTPUT

      ---
      Note: Large diffs may be truncated per-file. Use 'git diff' or 'git show' for full content if needed.

      Use 'glab mr note $MR_NUMBER --message <comment>' to post comments to the MR."

      if [ -n "$EXTRA_CONTEXT" ]; then
        PROMPT="$PROMPT

      Additional Context:
      $EXTRA_CONTEXT"
      fi

      ~/.checksumai/callagents.sh pull-request-tester "$PROMPT"
