# Checksum CI Guard - Base Template
# Users extend this job and provide required variables
#
# Usage:
#   include:
#     - remote: 'https://raw.githubusercontent.com/checksum-ai/checksum-action/main/ci-guard/gitlab-ci.yml'
#
#   checksum-ci-guard:
#     extends: .checksum-ci-guard-base
#     rules:
#       - if: $CI_PIPELINE_SOURCE == "merge_request_event"
#     variables:
#       CHECKSUM_API_KEY: $CHECKSUM_API_KEY
#       MR_NUMBER: $CI_MERGE_REQUEST_IID
#       PROJECT_PATH: $CI_PROJECT_PATH
#       MR_TITLE: $CI_MERGE_REQUEST_TITLE
#       MR_URL: "$CI_PROJECT_URL/-/merge_requests/$CI_MERGE_REQUEST_IID"
#       BASE_SHA: $CI_MERGE_REQUEST_DIFF_BASE_SHA
#       HEAD_SHA: $CI_COMMIT_SHA
#       MR_DESCRIPTION: $CI_MERGE_REQUEST_DESCRIPTION

.checksum-ci-guard-base:
  image: debian:bookworm-slim  # Debian-based for glibc compatibility with e2e-agent binary

  variables:
    GIT_DEPTH: 0

  before_script:
    - apt-get update && apt-get install -y --no-install-recommends curl jq bash ripgrep ca-certificates git

  script:
    - |
      if [ -z "$CHECKSUM_API_KEY" ]; then
        echo "Error: CHECKSUM_API_KEY is required"
        exit 1
      fi
      if [ -z "$MR_NUMBER" ]; then
        echo "Error: MR_NUMBER is required"
        exit 1
      fi

      # Debug: Log API key (masked) and create .env BEFORE install
      echo "DEBUG: CHECKSUM_API_KEY length: ${#CHECKSUM_API_KEY}"
      echo "DEBUG: CHECKSUM_API_KEY first 4 chars: ${CHECKSUM_API_KEY:0:4}..."

      # Create .env file BEFORE install (in case install.sh validates)
      mkdir -p ~/.checksumai
      echo "CHECKSUM_API_KEY=$CHECKSUM_API_KEY" > ~/.checksumai/.env
      chmod 600 ~/.checksumai/.env
      echo "DEBUG: .env file created at ~/.checksumai/.env"
      echo "DEBUG: .env contents (masked): $(head -c 20 ~/.checksumai/.env)..."

      curl -fsSL "https://storage.googleapis.com/checksum-agent-public/install.sh?$(date +%s)" | bash -s -- --pr-review

      # Debug: Verify .env file still exists after install
      echo "DEBUG: .env exists after install: $(test -f ~/.checksumai/.env && echo 'yes' || echo 'no')"
      echo "DEBUG: .env contents after install (masked): $(head -c 20 ~/.checksumai/.env)..."
      ls -la ~/.checksumai/

      ~/.checksumai/callagents.sh pull-request-tester "You are reviewing a GitLab Merge Request.

      Review MR !$MR_NUMBER in $PROJECT_PATH.

      MR Title: $MR_TITLE
      MR URL: $MR_URL
      Base SHA: $BASE_SHA
      Head SHA: $HEAD_SHA

      MR Description:
      $MR_DESCRIPTION

      Use 'git diff $BASE_SHA..$HEAD_SHA' to see the changes.

      To post comments, use curl with GitLab API:
      curl --request POST --header \"PRIVATE-TOKEN: \$GITLAB_TOKEN\" --form \"body=<comment>\" \"https://\$CI_SERVER_HOST/api/v4/projects/\$CI_PROJECT_ID/merge_requests/$MR_NUMBER/notes\""
